name = "oggyhosting"
type = "javascript"
account_id = "574f06d98127b4c90aae909014cc758d"
main = "worker.js"
compatibility_date = "2025-06-03"

kv_namespaces = [
  { binding = "MYBOTS_KV", id = "0e4b34b4eebf43efb318e2a5ec08c9a5" }
]
